### ISSUE TITLE
Relative Link Not Working

### ISSUE THREAD

**Issue by rdonnelly** [trentm/python-markdown2#254]
Hi there,

I'm trying to use a relative link and the markup coming out is not what I would expect:

```markdown
[Overview](#overview)
[Overview](/overview)
[Overview](overview)
[Overview](http://google.com/overview)
```

and I'm getting:

```html
<a href="#">Overview</a>
<a href="#">Overview</a>
<a href="#">Overview</a>
<a href="http://google.com/overview">Overview</a>
```

I am hoping I am just missing something. Let me know if there's anything else I can provide. Thanks for your time!

**Comment by nicholasserra** [comment]
Hm, looks like a bug. Thanks for the report :)

**Comment by rdonnelly** [comment]
Late follow-up, but actually it looks like the issue goes away when `safe_mode` is activated. Thanks for the reply!

**Comment by BrendaH** [comment]
So, can this be used outside of safe_mode, and if so: how?

I'm using [django-machina](https://github.com/ellmetha/django-machina) which uses Markdown2, but relative links are not working.

Instead of doing this:
`[Link](http://127.0.0.1:8000/nl/forum/forum/safety-67/topic/first-topic-242/)`
I'd like to be able to do this:
`[Link](/forum/safety-67/topic/first-topic-242/)`
Or perhaps, only omitting the base url, because how would Markdown know that it is used inside a forum?
`[Link](/forum/forum/safety-67/topic/first-topic-242/)`

Since this issue is still open I'm wondering if relative links are possible, and if so: how?
If the way it is supposed to work is not compatible with django-machina then I can go look there for a solution.

**Comment by pknowles** [comment]
I had an old `markdown2==2.3.1` project and never had this issue. After updating to master (currently bf3a3fd) I just hit this issue. That's a big bisect, but this seems like a regression. I've been using `safe_mode="escape"`.

**Comment by nicholasserra** [comment]
@pknowles could you show the input and output you're seeing? Thanks!

**Comment by pknowles** [comment]
Sure. Here's some full examples. All the failures below end up being `<a href="#">...` links

```
- [link1 works](https://www.hostname.com/absolute/path)
- [link2 works](https://www.hostname.com/absolute/path#anchor-on-another-page)
- [link3 works](#anchor-on-this-page)
- [link4 fails](/)
- [link5 fails](/absolute/path)
- [link6 fails](../relative/path)
```
