### ISSUE TITLE
two lists

### ISSUE THREAD

**Issue by NickeZ** [trentm/python-markdown2#313]
Hey,

is this expected behaviour? It looks very weird. The middle items get wrapped in `<p></p>`

```
>>> markdown2.markdown('* item A\n* Item B\n\n* Item C\n* Item D\n')
'<ul>\n<li>item A</li>\n<li><p>Item B</p></li>\n<li><p>Item C</p></li>\n<li>Item D</li>\n</ul>\n'
```

**Comment by nicholasserra** [comment]
Looks valid. Wondering why some are wrapped with paragraph and some aren't. What's the input?

**Comment by NickeZ** [comment]
The input is

```
* Item A
* Item B

* Item C
* Item D
```

The middle two get wrapped in paragraphs.

**Comment by nicholasserra** [comment]
Thanks! Yeah kind of odd. We'll leave this open if anyone wants to take a shot at it.

**Comment by Crozzers** [comment]
I looked into this and it seems to be intentional behaviour.

Each list item gets processed by the `_list_item_sub` function and [line 1784](https://github.com/trentm/python-markdown2/blob/bc175ad7a65ce24f5fb781dd0c12577078cc6109/lib/markdown2.py#L1784) is the line that decides whether to run the list item through the `_run_block_gamut` function.
```python
        if leading_line or '\n\n' in item or self._last_li_endswith_two_eols:
            item = self._run_block_gamut(self._outdent(item))
```

When `* Item B\n\n` comes in, it gets passed through the block gamut and subsequently gets passed through `_form_paragraphs` which wraps it in `<p></p>` tags.
The `_last_li_endswith_two_eols` class variable then gets set to `True` since the last item ended with `\n\n`, meaning that when the next item (`* Item C\n`) comes in, it will also get run through `_run_block_gamut` resulting in it being wrapped in `<p></p>` tags.

I ran the same sample input through the perl implementation and [python-markdown](https://github.com/Python-Markdown/markdown) as a sanity check and they both produced the same result

**Comment by ambv** [comment]
Good catch with the intended behavior, @Crozzers. This is because list items in Markdown can have a so-called "paragraph mode". Here's an interesting comment by John Gruber about it:

https://web.archive.org/web/20181229032814/http://article.gmane.org:80/gmane.text.markdown.general/2554

In the thread Gruber suggests using two blank lines to separate consecutive lists but neither CommonMark nor Python-Markdown nor markdown2 do it. However, CommonMark improves on the "mixed" paragraph style that is output by markdown2, Python-Markdown, and Markdown.pl. In case of CommonMark, an existence of a paragraph-style element in a list converts the entire list to paragraph style, which in general makes it format more consistently.

This is up to the maintainers like @nicholasserra to determine whether they'd like to diverge from Python-Markdown and Markdown.pl for this one and make the behavior like CommonMark. In the mean time I added an example to tests that shows that the current behavior is at least somewhat deliberate.

**Comment by nicholasserra** [comment]
Gonna close this for now as this is working correctly at least from the code perspective. I don't really have the desire to diverge from the other packages, unless someone comes up with a good reason.
