### ISSUE TITLE
render wavedrom in code block

### ISSUE THREAD

**Issue by PyroTom** [trentm/python-markdown2#467]
For documentation purposes its really nice to create diagrams easily using `code`.

It would be nice if you can support wavedrom.
https://wavedrom.com/

> ```wavedrom
> {signal: [
>   {name: 'clk', wave: 'p.....|...'},
>   {name: 'dat', wave: 'x.345x|=.x', data: ['head', 'body', 'tail', 'data']},
>   {name: 'req', wave: '0.1..0|1.0'},
>   {},
>   {name: 'ack', wave: '1.....|01.'}
> ]}
> ```

**Comment by Crozzers** [comment]
Hi there! I'm working an implementation of this feature using the [wavedrom python package](https://pypi.org/project/wavedrom/). So far, in order to use it you put your waves inside a fenced code block, setting "wavedrom" as the language like so:
````
Some text and information
```wavedrom
{ "signal": [{ "name": "Alfa", "wave": "01.zx=ud.23.456789" }] }
```
````
The wavedrom extra will then render and directly embed the resulting SVG into the output like so:
```
<p>Some text and information</p>

<div>
<svg ...>[Massive block of SVG stuff]</svg>
</div>
```

Was this the kind of implementation you had in mind?
If all goes well I'm hoping to submit a PR after #466 is merged, as this feature requires an optional dependency

**Comment by Crozzers** [comment]
Just added a commit that will allow the SVG embedding to be disabled. If this is the case, or if the wavedrom python package is not installed, then the extra will wrap the code in `<script type="WaveDrom">...</script>` tags, as the [Wavedrom README](https://github.com/wavedrom/wavedrom#html-pages) suggests.
This means that you can then link to the Wavedrom JS file instead of having a massive blob of SVG in the middle of your HTML file.

To control the SVG embedding, one would pass the wavedrom extra as a `dict` like so:
```python
import markdown2
markdown2.markdown("[some stuff]", extras={"wavedrom": {"prefer_embed_svg": False}})
```

**Comment by PyroTom** [comment]
Yeah that's exactly what i had in my mind 😍

I am already using the javascript directly as workaround. 
https://github.com/mitmproxy/pdoc/issues/406
