### ISSUE TITLE
Python code snippet that include comments do not get parsed correctly

### ISSUE THREAD

**Issue by BenjaminScholtens** [trentm/python-markdown2#515]
The below python code snippet does not get converted from markdown to html correctly. 

```python
# This is a python comment that is incorrectly converted to a h1

num = 12
print(num ** num)
```
The comment in the middle of the code snippet is converted to an html h1 and breaks the continuity of the code snippet.

**Comment by Crozzers** [comment]
Hi there! I'm unable to reproduce this issue. Could you attach a markdown snippet that demonstrates the problem? If you're using fenced code blocks in your markdown, you can wrap the outer fence in 4 backticks instead of 3 to escape it for GitHub. EG:
````
^ 4 backticks
```python
my code
```
````
And also which version of the library are you using?

Cheers

**Comment by BenjaminScholtens** [comment]
Hi @Crozzers, Thanks for the 4 backticks tip. Here is the example. 

````
### this is a md test


```
# This is a python comment that is INCORRECTLY converted to a h1

num = 12
print(num ** num)
```

# this is a md test 2
````

**Comment by Crozzers** [comment]
Are you using the [fenced-code-blocks](https://github.com/trentm/python-markdown2/wiki/fenced-code-blocks) extra?

**Comment by BenjaminScholtens** [comment]
Hey @Crozzers , I did not know that fenced-code-blocks needed to be enabled. Thanks for the tip that fixed it.
