### ISSUE TITLE
Regression for **bolded_code_friendly** text

### ISSUE THREAD

**Issue by mhils** [trentm/python-markdown2#589]
**Describe the bug**
Starting with fcaadfe9e6145e3e2f11e041e00a0b7df857c2e2, markdown2 renders `_` as `<em>` in bolded text, even if `code-friendly` is set. @Crozzers, any idea on what's the best way to fix this?

**To Reproduce**
```
**bold_but_not_emphasized**
```

Full test case: https://github.com/mhils/python-markdown2/commit/bf39e38ab19d2d7ff9cdd4b09edc244087ca6dc6

**Expected behavior**

`_` should stay as-is.

**Additional context**

Thank you so much for the other changes in 2.5.0, it's fantastic! 🍰

**Comment by Crozzers** [comment]
When I added the `CodeFriendly` extra class I had to change the program flow a bit, since it was no longer directly part of the `_do_italics_and_bold` function.

Previously we had two different versions of the strong/em regexes and we'd run one or the other. That's not possible in the new `Extra`s format so the `CodeFriendly` extra runs before italics and bold and hashes text to protect it from the regex.

Currently it only hashes text if it's using the `_underscore bold syntax_`, but for `*star syntax*` it doesn't check if the text contains any underscores, which is how this can slip through.

I'll modify the extra to check for this and hash the text to protect it
