### ISSUE TITLE
Unable to detect non-breaking space

### ISSUE THREAD

**Issue by aidanho1188** [trentm/python-markdown2#592]
**Describe the bug**
When a non-breaking character like non-breaking space (&nbsp;) is present in the markdown, it is returned as � in the HTML output.

**To Reproduce**

```
Topics:

- React State; `useState` and `setState`.
- React Style; `style` and `className`props.
- Passing `props` to child components.
- React and CSS
```

**Expected behavior**
I'm expecting that non-breaking space from the md file should convert to this `&nbsp;` HTML entity.

**Debug info**
Version of library being used: 2.5.0

Any extras being used:

**Additional context**

**Comment by Crozzers** [comment]
I tried this locally and wasn't able to reproduce it. How are you invoking the library? Is safe mode being used?

**Comment by aidanho1188** [comment]
Thank you for looking into this issue! I discovered that this bug only happens when I use the CLI script. If you copy the Markdown above, put it in a Markdown file, and have markdown2.py in your folder, then run the script, you will see the bug.

![image](https://github.com/user-attachments/assets/1272c44a-d68a-4701-ba95-21d2a8a92d22)

**Comment by Crozzers** [comment]
Tried locally again and could not reproduce. Maybe it's an encoding issue? Do you know what the encoding is of the markdown file?

**Comment by Crozzers** [comment]
Cannot reproduce this at all. I put the sample text in a UTF-8 markdown file, invoked the library through the command line as shown in the screenshot and opened the file in VSCode. The non-breaking spaces appear normal.

The output file is written as UTF-8 by default, so the only way I could get close to the issue is by opening the file in a different encoding like Windows 1252.

I'm wondering if the text is intact and it's just an issue with how VSCode is displaying it. Have you checked what encoding VSCode is opening it with or checking it in a browser to see if that works?

**Comment by aidanho1188** [comment]
It appears that when I use the script, the encoding changes from UTF-8 to ISO-8859-1. I tested this on Codespace on GitHub and everything worked fine. Then, I tried it on a clean virtual environment and reinstalled VSCode, but the problem is there. I did some more testing and found out that the problem is related to the system locale setting.

![image](https://github.com/user-attachments/assets/98030b36-1ae0-4494-a4f4-f547cdeb4627)

Checking the beta box for “Use Unicode UTF-8 for worldwide language support” in the system locale settings seems to fix the problem. 

Thank you so much for your help with debugging the issue. I really appreciate it! @Crozzers
